Task3
kszytko/object-oriented-programming pull request #17
Opened 2020-06-17 21:02 UTC by Nessy90

2020-06-17 23:58 UTC, kszytko approved these changes

2020-06-18 07:37 UTC, madebykj approved these changes

2020-06-18 10:46 UTC, madebykj requested changes
Please add file Island.cpp with line #include "Island.hpp"

2020-06-18 10:50 UTC, KrzysztofJ85 commented on shm/Coordinates.cpp
> +}
I think that we don't need this at the moment.

2020-06-18 14:05 UTC, KrzysztofJ85 commented
From https://coders.school/edu/courses/obiektowosc-1/lesson/projekt-grupowy/ Task 6 description I assume, that Class Coordinates should be part of Class Island. In our situation it is not, so instead of Island* getIsland(const Island::Coordinates& coordinate) in Task 6 I have put Island* getIsland(const Coordinates& coordinate). Otherwise it doesn't work. Correct me if I'm wrong.

2020-06-18 15:47 UTC, madebykj approved these changes

2020-06-18 16:00 UTC, merged

2020-06-18 20:05 UTC, lksobczyk commented on shm/Coordinates.cpp
> +    return !(this == coordinatesToCheck);
return !(*this == coordinatesToCheck);

2020-06-18 20:13 UTC, lksobczyk commented on shm/Coordinates.hpp
> +    const int _positionY;
Why _positionX and _positionY are constant?