Task 4: Map (new class) #4
kszytko/object-oriented-programming pull request #18
Opened 2020-06-18 11:29 UTC by KrzysztofJ85

2020-06-18 20:34 UTC, lksobczyk commented on shm/Map.cpp
> +            vecOfIslands_.emplace_back(Island(positionX, positionY));
Excellently

2020-06-18 20:37 UTC, lksobczyk requested changes
Could you use prefix instead of suffix for fields in class?

2020-06-18 20:55 UTC, lksobczyk reviewed
Also add "Map.o" to Makefile

2020-06-19 09:39 UTC, lksobczyk approved these changes
Well done.

2020-06-19 16:06 UTC, kszytko requested changes

2020-06-19 16:06 UTC, kszytko commented on shm/Map.cpp
> +    }
It's a good place for future refactoring.
You have constant value in header file `numberOfIslands` - use it instead `!= 10`

2020-06-19 16:06 UTC, kszytko commented on shm/Map.hpp
> +constexpr int randomNumberStart = 1;
It's better to have one naming concept. 
```suggestion
constexpr int minPositionXY = 1;
```

2020-06-20 21:43 UTC, lksobczyk approved these changes

2020-06-20 21:45 UTC, kszytko approved these changes
Good

2020-06-20 21:45 UTC, merged