Kszytko
kszytko/object-oriented-programming pull request #32
Opened 2020-06-24 17:12 UTC by kszytko

2020-06-25 13:54 UTC, lksobczyk requested changes

2020-06-25 13:54 UTC, lksobczyk commented on shm/Cargo.cpp
> +    if (_amount + amount) {
```suggestion
    if (_amount < amount) {
```

2020-06-26 01:07 UTC, lksobczyk approved these changes
It's all right.

2020-06-26 15:51 UTC, Nessy90 approved these changes

2020-06-26 15:59 UTC, merged

2020-06-26 16:24 UTC, Tomonike reviewed
It's looks ok.