Basic classes outline
kszytko/object-oriented-programming pull request #35
Opened 2020-06-26 19:06 UTC by lksobczyk

2020-06-26 20:01 UTC, Tomonike approved these changes
It's look good.

2020-06-27 18:41 UTC, Nessy90 requested changes

2020-06-27 18:41 UTC, Nessy90 commented on shm/Game.hpp
> +    size_t _final_goal;
maybe let's stick to camel case :)

2020-06-27 18:41 UTC, Nessy90 commented on shm/Time.cpp
> +    ++_time_elapsed;
camel case :)

2020-06-27 18:41 UTC, Nessy90 commented on shm/main.cpp
> +constexpr size_t final_goal = 2'000;
camel case

2020-06-27 19:31 UTC, Nessy90 approved these changes

2020-06-27 19:42 UTC, merged